"""add user profiles and holdings

Revision ID: 71ad9151192c
Revises: 20260804_add_stock_schema
Create Date: 2026-08-07 09:49:10.171032
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ad9151192c'
down_revision = '20260804_add_stock_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_cost_basis', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=32), nullable=True),
    sa.Column('investment_goals', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("experience_level IS NULL OR experience_level IN ('beginner', 'intermediate', 'advanced')", name='ck_user_profiles_experience_level'),
    sa.CheckConstraint("risk_tolerance IS NULL OR risk_tolerance IN ('conservative', 'moderate', 'aggressive')", name='ck_user_profiles_risk_tolerance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
