import fs from "node:fs/promises";

const pages = await fetch("http://127.0.0.1:9224/json/list").then((response) => response.json());
const page = pages.find((item) => item.type === "page");
if (!page) throw new Error("No Chrome page target found");
const socket = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((resolve, reject) => { socket.addEventListener("open", resolve, { once: true }); socket.addEventListener("error", reject, { once: true }); });
let id = 0;
const pending = new Map();
socket.addEventListener("message", (event) => { const message = JSON.parse(event.data); const handler = pending.get(message.id); if (!handler) return; pending.delete(message.id); message.error ? handler.reject(new Error(message.error.message)) : handler.resolve(message.result); });
const command = (method, params = {}) => { const requestId = ++id; socket.send(JSON.stringify({ id: requestId, method, params })); return new Promise((resolve, reject) => pending.set(requestId, { resolve, reject })); };
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const evaluate = async (expression) => { const result = await command("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.text); return result.result.value; };
const waitFor = async (expression, timeout = 30000) => { const started = Date.now(); while (Date.now() - started < timeout) { if (await evaluate(expression)) return; await sleep(250); } throw new Error(`Timed out: ${expression}`); };
const screenshot = async (name) => { const result = await command("Page.captureScreenshot", { format: "png", captureBeyondViewport: true }); await fs.writeFile(`artifacts/${name}.png`, Buffer.from(result.data, "base64")); };

await command("Page.enable");
await command("Runtime.enable");
await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
await command("Page.navigate", { url: "http://localhost:3000/login" });
await waitFor("Boolean(document.querySelector('#email'))");
await sleep(1200);
await evaluate(`(() => { const set = (selector, value) => { const element = document.querySelector(selector); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(element, value); element.dispatchEvent(new Event('input', { bubbles: true })); }; set('#email', 'test@example.com'); set('#password', 'testpass123'); document.querySelector('form').requestSubmit(); })()`);
await waitFor("location.pathname === '/dashboard'");
await waitFor("[...document.querySelectorAll('button')].some((button) => button.textContent.trim() === 'History')");
await evaluate("[...document.querySelectorAll('button')].find((button) => button.textContent.trim() === 'History').click()");
await waitFor("document.body.innerText.includes('Previous chats') && document.body.innerText.includes('Summarize MSFT momentum.') && document.body.innerText.includes('Explain why portfolio diversification matters.')");
const history = await evaluate(`({ hasHistoryTitle: document.body.innerText.includes('Previous chats'), hasMsft: document.body.innerText.includes('Summarize MSFT momentum.'), hasDiversification: document.body.innerText.includes('Explain why portfolio diversification matters.'), relativeTimestamp: document.body.innerText.includes('ago') || document.body.innerText.includes('Just now') })`);
await screenshot("user-chat-history");
await evaluate("[...document.querySelectorAll('button')].find((button) => button.innerText.includes('Summarize MSFT momentum.')).click()");
await waitFor("document.body.innerText.includes('Microsoft (MSFT) is currently trading')");
const reopened = await evaluate(`({ hasUserRole: document.body.innerText.includes('You'), hasAssistantRole: document.body.innerText.includes('AI'), hasQuestion: document.body.innerText.includes('Summarize MSFT momentum.'), hasAnswer: document.body.innerText.includes('Microsoft (MSFT) is currently trading') })`);
await screenshot("user-chat-reopened");
const followup = "Does that momentum fit my earlier interest in AI companies?";
await evaluate(`(() => { const input = [...document.querySelectorAll('input')].find((item) => item.placeholder.startsWith('Ask about')); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, ${JSON.stringify(followup)}); input.dispatchEvent(new Event('input', { bubbles: true })); [...document.querySelectorAll('button')].find((button) => button.textContent.trim() === 'Send').click(); })()`);
await waitFor(`document.body.innerText.includes(${JSON.stringify(followup)})`);
await waitFor("![...document.querySelectorAll('button')].some((button) => button.textContent.includes('Thinking'))", 60000);
await screenshot("user-chat-continued");
console.log(JSON.stringify({ history, reopened, continuedInOpenView: await evaluate(`document.body.innerText.includes(${JSON.stringify(followup)})`) }, null, 2));
socket.close();
